apiVersion: v1
kind: Service
metadata:
  name: youtube-summarizer
  namespace: youtube-summarizer
  labels:
    app: youtube-summarizer
spec:
  type: ClusterIP
  selector:
    app: youtube-summarizer
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    protocol: TCP
